name: haskell-web-repl
version: '0.1.0.0'

author: yamadapc
maintainer: tacla.yamada@gmail.com
license: BSD3

extra-source-files:
- README.md

dependencies:
- base >=4 && <5
- bytestring >=0.10.8.1
- websockets
- conduit
- conduit-extra
- text

executables:
  haskell-web-repl:
    main: backend.hs
    source-dirs: '.'
